version: '2'

services:
  container_nginx:
    build:
      context: .
      dockerfile: Dockerfile6
    container_name: container_nginx
    tty: true
    
  server:
    build: part_6/
    ports:
      - 80:8080
    tty: true
    depends_on:
      - container_nginx
